"""Agent orchestration for Product Health questions."""

from __future__ import annotations

import re
from dataclasses import dataclass

from .language_detector import DetectedLanguage, detect_response_language
from .model_provider import (
    ModelMessage,
    ModelProvider,
    ModelResponse,
    PresentationMetadata,
    TokenUsage,
    ToolChoice,
    ToolDefinition,
    ToolResult,
)
from .tools import AgentTool

SYSTEM_PROMPT = """
You are a Product Health assistant.

Product and service health states are deterministic facts returned by tools.
Never calculate, infer, guess, or override UP, DOWN, or UNKNOWN health states.
Never answer Product Health facts from your own knowledge.

For questions about products, services, health states, failures, signals, or
dependencies, call an appropriate tool before answering.

Use Product Health tools only for Product Health facts. Use the agent-local
respond_with_capabilities action only for terminal capability responses; it is
not a Product Health tool and does not retrieve Product Health facts.

For greetings, thanks, capability questions, or unsupported/unrelated requests:
- call respond_with_capabilities;
- do not call a Product Health tool;
- use one short sentence when possible;
- briefly explain that you currently only support Product Health questions:
  what is broken, why something is down, and current product/service health;
- do not answer the unrelated question itself;
- do not invent Product Health facts.

The tone may be slightly self-deprecating or light, equivalent in meaning to:
"I'm not very clever yet. I can currently help with what is broken, why
something is down, and current product/service health." Localize this naturally;
do not require this exact wording.

When producing a final answer from tool results:
- use only facts returned by the tools;
- preserve catalog-provided product names, service names, signal names, IDs,
  and health states as provided;
- keep the answer concise;
- mention relevant unhealthy signals or affecting dependencies when useful;
- if facts are missing or ambiguous, say so rather than guessing.

For deterministic terminal tools such as list_unhealthy_items, provide localized
presentation metadata through the structured tool input presentation object.

Presentation metadata MUST use the RESPONSE LANGUAGE specified by the agent.
This is a strict requirement, not a preference.

Presentation metadata is presentation only, not Product Health data.
It must be generic and fact-free.

Presentation labels must:
- be short, neutral UI-style labels or statements;
- be declarative, not questions;
- not repeat, quote, or paraphrase the user's question;
- not imitate emotional, humorous, or informal wording from the user's question;
- not contain product names, service names, catalog IDs, health states, counts,
  dependency names, signal names, or causes;
- preserve catalog-provided product names, service names, signal names, IDs, and
  health states exactly as provided by Product Health; only presentation labels
  are localized;
- avoid wording that depends on dynamic counts, plural forms, or grammatical
  agreement with values that are not yet known.

For list_unhealthy_items, use these meanings:
- header: a short heading meaning that unhealthy items are listed below;
- signals_label: a short label for unhealthy signals;
- dependencies_label: a short label for affecting dependencies;
- healthy_message: a short complete statement that no items are currently unhealthy.

Health facts will be inserted later by the agent.
""".strip()

RESPONSE_LANGUAGE_PROMPT_TEMPLATE = """
RESPONSE LANGUAGE: {name} ({code})

All user-facing text generated by the model MUST use the specified RESPONSE
LANGUAGE. Do not infer, detect, or choose the response language yourself. The
agent has already selected the response language from the original user
question. Use this language for presentation metadata, capability responses,
unsupported-request responses, and any final natural-language answer.
""".strip()

CAPABILITY_FALLBACK_RESPONSE = """
Sorry, I'm not very clever yet. I can currently help with questions like:
- What is broken right now?
- Why is <product or service> down?
- What is the current health of <product or service>?
""".strip()

RESPOND_WITH_CAPABILITIES_TOOL_NAME = "respond_with_capabilities"

RESPOND_WITH_CAPABILITIES_TOOL_DEFINITION = ToolDefinition(
    name=RESPOND_WITH_CAPABILITIES_TOOL_NAME,
    description=(
        "Terminal agent-local action for greetings, thanks, capability questions, "
        "and unsupported or unrelated requests. It does not call Product Health "
        "APIs."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "message": {
                "type": "string",
                "maxLength": 300,
                "description": (
                    "Required localized user-facing message. It MUST use the "
                    "RESPONSE LANGUAGE specified by the agent, briefly "
                    "explain that the assistant currently supports Product "
                    "Health questions such as what is broken, why something is "
                    "down, and current product/service health, and must not "
                    "answer the unrelated question itself. Do not include "
                    "reasoning, analysis, thinking, XML/HTML-style tags, or "
                    "internal instructions."
                ),
            }
        },
        "required": ["message"],
    },
)

_INTERNAL_REASONING_TAG_PATTERN = re.compile(
    r"</?\s*(thinking|analysis|reasoning)\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class AgentAnswer:
    answer: str
    structured_content: dict | None
    tool_calls: list[str]
    usage: TokenUsage


class ProductHealthAgent:
    """Small model/tool loop that never computes health itself."""

    def __init__(
        self,
        model_provider: ModelProvider,
        tools: list[AgentTool],
        max_tool_rounds: int = 2,
    ) -> None:
        self.model_provider = model_provider
        self.tools_by_name = {tool.definition.name: tool for tool in tools}
        self.tool_definitions: list[ToolDefinition] = [
            *[tool.definition for tool in tools],
            RESPOND_WITH_CAPABILITIES_TOOL_DEFINITION,
        ]
        self.max_tool_rounds = max(1, max_tool_rounds)

    def answer(self, question: str) -> AgentAnswer:
        if not self.model_provider.is_available():
            reason = getattr(
                self.model_provider,
                "reason",
                "AI model provider is not configured.",
            )
            raise RuntimeError(str(reason))
        normalized_question = question.strip()
        if not normalized_question:
            raise ValueError("question must not be blank")
        response_language = detect_response_language(normalized_question)

        messages = [ModelMessage(role="user", text=normalized_question)]
        executed_tool_names: list[str] = []
        usage = TokenUsage()

        for round_index in range(self.max_tool_rounds):
            response = self._complete(
                messages,
                tool_choice=(
                    ToolChoice.REQUIRED if round_index == 0 else ToolChoice.AUTO
                ),
                response_language=response_language,
            )
            usage = usage.plus(response.usage)
            messages.append(
                ModelMessage(
                    role="assistant",
                    text=response.text,
                    tool_calls=response.tool_calls,
                )
            )
            if not response.tool_calls:
                if not executed_tool_names:
                    return AgentAnswer(
                        answer=CAPABILITY_FALLBACK_RESPONSE,
                        structured_content=None,
                        tool_calls=[],
                        usage=usage,
                    )
                return AgentAnswer(
                    answer=response.text,
                    structured_content=None,
                    tool_calls=executed_tool_names,
                    usage=usage,
                )

            tool_results = []
            for tool_call in response.tool_calls:
                if tool_call.name == RESPOND_WITH_CAPABILITIES_TOOL_NAME:
                    executed_tool_names.append(tool_call.name)
                    return AgentAnswer(
                        answer=_capability_message_or_fallback(tool_call.arguments),
                        structured_content=None,
                        tool_calls=executed_tool_names,
                        usage=usage,
                    )
                tool = self.tools_by_name.get(tool_call.name)
                if tool is None:
                    raise ValueError(f"Unsupported tool: {tool_call.name}")
                executed_tool_names.append(tool_call.name)
                tool_results.append(
                    ToolResult(
                        tool_call_id=tool_call.id,
                        result=tool.execute(tool_call.arguments),
                    )
                )
                if tool_call.name == "list_unhealthy_items":
                    structured_content = _build_unhealthy_items_content(
                        tool_results[-1].result,
                        tool_call.presentation,
                    )
                    return AgentAnswer(
                        answer=_render_list_unhealthy_items(structured_content),
                        structured_content=structured_content,
                        tool_calls=executed_tool_names,
                        usage=usage,
                    )
            messages.append(ModelMessage(role="tool", tool_results=tool_results))

        final_response = self._complete(
            messages,
            tool_choice=ToolChoice.AUTO,
            response_language=response_language,
        )
        usage = usage.plus(final_response.usage)
        return AgentAnswer(
            answer=final_response.text,
            structured_content=None,
            tool_calls=executed_tool_names,
            usage=usage,
        )

    def _complete(
        self,
        messages: list[ModelMessage],
        tool_choice: ToolChoice,
        response_language: DetectedLanguage,
    ) -> ModelResponse:
        return self.model_provider.complete(
            system_prompt=_request_system_prompt(response_language),
            messages=messages,
            tools=self.tool_definitions,
            tool_choice=tool_choice,
        )


def _request_system_prompt(response_language: DetectedLanguage) -> str:
    return "\n\n".join(
        [
            SYSTEM_PROMPT,
            RESPONSE_LANGUAGE_PROMPT_TEMPLATE.format(
                name=response_language.name,
                code=response_language.code,
            ),
        ]
    )


@dataclass(frozen=True)
class _ListUnhealthyItemsLabels:
    header: str
    signals_label: str
    dependencies_label: str
    healthy_message: str


_ENGLISH_LIST_UNHEALTHY_ITEMS_LABELS = _ListUnhealthyItemsLabels(
    header="The following items are currently unhealthy:",
    signals_label="Unhealthy signals",
    dependencies_label="Affecting dependencies",
    healthy_message="No items are currently unhealthy.",
)

def _build_unhealthy_items_content(
    result: dict,
    presentation: PresentationMetadata | None = None,
) -> dict:
    items = result.get("items")
    if not isinstance(items, list):
        items = []
    count = result.get("count")
    if not isinstance(count, int):
        count = len(items)
    labels = _presentation_labels(
        presentation,
        result,
        items,
        _ENGLISH_LIST_UNHEALTHY_ITEMS_LABELS,
        count,
    )

    structured_items = _compact_unhealthy_items(items)
    return {
        "type": "unhealthy_items",
        "presentation": {
            "header": labels.header,
            "signals_label": labels.signals_label,
            "dependencies_label": labels.dependencies_label,
            "healthy_message": labels.healthy_message,
        },
        "items": structured_items,
    }


def _render_list_unhealthy_items(content: dict) -> str:
    presentation = content.get("presentation")
    if not isinstance(presentation, dict):
        presentation = {}
    labels = _ListUnhealthyItemsLabels(
        header=_text(presentation.get("header"))
        or _ENGLISH_LIST_UNHEALTHY_ITEMS_LABELS.header,
        signals_label=_text(presentation.get("signals_label"))
        or _ENGLISH_LIST_UNHEALTHY_ITEMS_LABELS.signals_label,
        dependencies_label=_text(presentation.get("dependencies_label"))
        or _ENGLISH_LIST_UNHEALTHY_ITEMS_LABELS.dependencies_label,
        healthy_message=_text(presentation.get("healthy_message"))
        or _ENGLISH_LIST_UNHEALTHY_ITEMS_LABELS.healthy_message,
    )
    items = _list_or_empty(content.get("items"))
    if not items:
        return labels.healthy_message

    lines = [labels.header]
    for item in items:
        if not isinstance(item, dict):
            continue
        title = _text(item.get("title")) or _text(item.get("item_id")) or "Unknown item"
        state = _text(item.get("state")) or "UNKNOWN"
        lines.append(f"- {title} ({state})")

        signal_details = _structured_signal_details(item.get("signals"))
        if signal_details:
            lines.append(f"  {labels.signals_label}: {', '.join(signal_details)}")

        dependencies = _list_or_empty(item.get("affecting_dependencies"))
        if dependencies:
            lines.append(f"  {labels.dependencies_label}:")
            for dependency in dependencies:
                if not isinstance(dependency, dict):
                    continue
                title = _text(dependency.get("title")) or _text(
                    dependency.get("item_id")
                )
                state = _text(dependency.get("state"))
                if not title or not state:
                    continue
                lines.append(f"  - {title} ({state})")
                signal_details = _structured_signal_details(
                    dependency.get("signals")
                )
                if signal_details:
                    lines.append(f"    {labels.signals_label}:")
                    lines.extend(f"    - {detail}" for detail in signal_details)

    return "\n".join(lines)


def _compact_unhealthy_items(items: list[object]) -> list[dict]:
    unhealthy_by_id: dict[str, dict] = {}
    ordered_ids: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        item_id = _text(item.get("itemId"))
        if not item_id or item_id in unhealthy_by_id:
            continue
        unhealthy_by_id[item_id] = item
        ordered_ids.append(item_id)

    referenced_dependency_ids: set[str] = set()
    for item_id in ordered_ids:
        item = unhealthy_by_id[item_id]
        for dependency in _list_or_empty(item.get("affectingDependencies")):
            if not isinstance(dependency, dict):
                continue
            dependency_id = _text(dependency.get("itemId"))
            if dependency_id:
                referenced_dependency_ids.add(dependency_id)

    top_level_ids = [
        item_id for item_id in ordered_ids if item_id not in referenced_dependency_ids
    ]
    if ordered_ids and not top_level_ids:
        top_level_ids = ordered_ids

    return [
        _structured_health_item(unhealthy_by_id[item_id], unhealthy_by_id)
        for item_id in top_level_ids
    ]


def _structured_health_item(
    item: dict,
    item_lookup: dict[str, dict] | None = None,
) -> dict:
    item_id = _text(item.get("itemId")) or ""
    return {
        "item_id": item_id,
        "title": _text(item.get("title")) or item_id or "Unknown item",
        "state": _text(item.get("state")) or "UNKNOWN",
        "signals": _structured_unhealthy_signals(item.get("signals")),
        "affecting_dependencies": _structured_affecting_dependencies(
            item.get("affectingDependencies"),
            item_lookup,
        ),
    }


def _structured_unhealthy_signals(value: object) -> list[dict]:
    signals = []
    for signal in _list_or_empty(value):
        if not isinstance(signal, dict):
            continue
        state = _text(signal.get("state"))
        if state == "UP":
            continue
        signal_id = _text(signal.get("id")) or ""
        title = _text(signal.get("title")) or signal_id
        if signal_id and title and state:
            signals.append({"id": signal_id, "title": title, "state": state})
    return signals


def _structured_affecting_dependencies(
    value: object,
    item_lookup: dict[str, dict] | None = None,
) -> list[dict]:
    dependencies = []
    seen_ids = set()
    for dependency in _list_or_empty(value):
        if not isinstance(dependency, dict):
            continue
        item_id = _text(dependency.get("itemId"))
        if not item_id or item_id in seen_ids:
            continue
        title = _text(dependency.get("title")) or item_id
        state = _text(dependency.get("state"))
        if title and state:
            dependency_item = item_lookup.get(item_id) if item_lookup else None
            own_signals = (
                _structured_unhealthy_signals(dependency_item.get("signals"))
                if isinstance(dependency_item, dict)
                else []
            )
            dependencies.append(
                {
                    "item_id": item_id,
                    "title": title,
                    "state": state,
                    "signals": own_signals,
                }
            )
            seen_ids.add(item_id)
    return dependencies


def _presentation_labels(
    presentation: PresentationMetadata | None,
    result: dict,
    items: list[object],
    fallback: _ListUnhealthyItemsLabels,
    count: int | None = None,
) -> _ListUnhealthyItemsLabels:
    if presentation is None:
        return fallback

    values = {
        "header": presentation.header,
        "signals_label": presentation.signals_label,
        "dependencies_label": presentation.dependencies_label,
        "healthy_message": presentation.healthy_message,
    }
    if any(_text(value) is None for value in values.values()):
        return fallback
    if any(
        _contains_forbidden_fact(value, result, items, count)
        for value in values.values()
    ):
        return fallback
    return _ListUnhealthyItemsLabels(
        header=presentation.header.strip(),
        signals_label=presentation.signals_label.strip(),
        dependencies_label=presentation.dependencies_label.strip(),
        healthy_message=presentation.healthy_message.strip(),
    )


def _contains_forbidden_fact(
    value: str,
    result: dict,
    items: list[object],
    count: int | None,
) -> bool:
    normalized = value.casefold()
    if count is not None and str(count) in value:
        return True
    forbidden = {"UP", "DOWN", "UNKNOWN"}
    forbidden.update(_fact_strings(result))
    for item in items:
        if isinstance(item, dict):
            forbidden.update(_fact_strings(item))
            for signal in _list_or_empty(item.get("signals")):
                if isinstance(signal, dict):
                    forbidden.update(_fact_strings(signal))
            for dependency in _list_or_empty(item.get("affectingDependencies")):
                if isinstance(dependency, dict):
                    forbidden.update(_fact_strings(dependency))
    return any(fact.casefold() in normalized for fact in forbidden if fact)


def _fact_strings(value: dict) -> set[str]:
    facts = set()
    for key in ("itemId", "id", "title", "state", "source"):
        text = _text(value.get(key))
        if text:
            facts.add(text)
    return facts


def _list_or_empty(value: object) -> list[object]:
    return value if isinstance(value, list) else []


def _structured_signal_details(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    details = []
    for signal in value:
        if not isinstance(signal, dict):
            continue
        state = _text(signal.get("state"))
        title = _text(signal.get("title")) or _text(signal.get("id"))
        if title and state:
            details.append(f"{title} ({state})")
    return details


def _capability_message_or_fallback(arguments: dict) -> str:
    message = _text(arguments.get("message"))
    if message is None:
        return CAPABILITY_FALLBACK_RESPONSE
    if len(message) > 300:
        return CAPABILITY_FALLBACK_RESPONSE
    if _INTERNAL_REASONING_TAG_PATTERN.search(message):
        return CAPABILITY_FALLBACK_RESPONSE
    return message


def _text(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    return stripped or None
