"""Agent orchestration for Product Health questions."""

from __future__ import annotations

import re
from dataclasses import dataclass

from .language_detector import DetectedLanguage, detect_response_language
from .model_provider import (
    ModelMessage,
    ModelProvider,
    ModelResponse,
    TokenUsage,
    ToolChoice,
    ToolDefinition,
    ToolResult,
)
from .tools import AgentTool

SYSTEM_PROMPT = """
You are a Product Health assistant.

Product and service health states are deterministic facts returned by tools.
Never calculate, infer, guess, or override UP, DOWN, or UNKNOWN health states.
Never answer Product Health facts from your own knowledge.

For questions about products, services, health states, failures, signals, or
dependencies, call an appropriate tool before answering.

Use Product Health tools only for Product Health facts. Use the agent-local
respond_with_capabilities action only for terminal capability responses; it is
not a Product Health tool and does not retrieve Product Health facts.

For greetings, thanks, capability questions, or unsupported/unrelated requests:
- call respond_with_capabilities;
- do not call a Product Health tool;
- use one short sentence when possible;
- briefly explain that you currently only support Product Health questions:
  what is broken, why something is down, and current product/service health;
- do not answer the unrelated question itself;
- do not invent Product Health facts.

The tone may be slightly self-deprecating or light, equivalent in meaning to:
"I'm not very clever yet. I can currently help with what is broken, why
something is down, and current product/service health." Localize this naturally;
do not require this exact wording.

When producing a final answer from tool results:
- use only facts returned by the tools;
- preserve catalog-provided product names, service names, signal names, IDs,
  and health states as provided;
- if facts are missing or ambiguous, say so rather than guessing.

For get_product_health and list_unhealthy_items results that the UI will render
as structured facts, your final answer is only a short introduction sentence.
It must:
- use the RESPONSE LANGUAGE;
- be one short sentence;
- be appropriate to the user's request and the actual tool result;
- not include dependency lists, signal lists, repeated facts, Markdown, HTML/XML
  tags, reasoning, analysis, or thinking;
- not add health summaries beyond the brief introduction.

The application renders item names, health states, signals, and dependencies
from structured tool results. Do not generate markup or the item/signal layout.
""".strip()

RESPONSE_LANGUAGE_PROMPT_TEMPLATE = """
RESPONSE LANGUAGE: {name} ({code})

All user-facing text generated by the model MUST use the specified RESPONSE
LANGUAGE. Do not infer, detect, or choose the response language yourself. The
agent has already selected the response language from the original user
question. Use this language for capability responses, unsupported-request
responses, structured-result introductions, and any final natural-language
answer.
""".strip()

CAPABILITY_FALLBACK_RESPONSE = """
Sorry, I'm not very clever yet. I can currently help with questions like:
- What is broken right now?
- Why is <product or service> down?
- What is the current health of <product or service>?
""".strip()

RESPOND_WITH_CAPABILITIES_TOOL_NAME = "respond_with_capabilities"
RESPOND_WITH_PRODUCT_HEALTH_INTRO_TOOL_NAME = "respond_with_product_health_intro"

RESPOND_WITH_CAPABILITIES_TOOL_DEFINITION = ToolDefinition(
    name=RESPOND_WITH_CAPABILITIES_TOOL_NAME,
    description=(
        "Terminal agent-local action for greetings, thanks, capability questions, "
        "and unsupported or unrelated requests. It does not call Product Health "
        "APIs."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "message": {
                "type": "string",
                "maxLength": 300,
                "description": (
                    "Required localized user-facing message. It MUST use the "
                    "RESPONSE LANGUAGE specified by the agent, briefly "
                    "explain that the assistant currently supports Product "
                    "Health questions such as what is broken, why something is "
                    "down, and current product/service health, and must not "
                    "answer the unrelated question itself. Do not include "
                    "reasoning, analysis, thinking, XML/HTML-style tags, or "
                    "internal instructions."
                ),
            }
        },
        "required": ["message"],
    },
)

RESPOND_WITH_PRODUCT_HEALTH_INTRO_TOOL_DEFINITION = ToolDefinition(
    name=RESPOND_WITH_PRODUCT_HEALTH_INTRO_TOOL_NAME,
    description=(
        "Terminal agent-local action for the one-sentence introduction shown "
        "above structured Product Health facts. It does not retrieve or modify "
        "Product Health data."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "introduction": {
                "type": "string",
                "maxLength": 220,
                "description": (
                    "Required localized one-sentence introduction. It MUST use "
                    "the RESPONSE LANGUAGE specified by the agent, be appropriate "
                    "to the user request and tool result, and must not include "
                    "dependency lists, signal lists, Markdown, HTML/XML-style "
                    "tags, reasoning, analysis, or thinking."
                ),
            }
        },
        "required": ["introduction"],
        "additionalProperties": False,
    },
)

_INTERNAL_REASONING_BLOCK_PATTERN = re.compile(
    r"<\s*(thinking|analysis|reasoning)\b[^>]*>.*?</\s*\1\s*>",
    re.IGNORECASE | re.DOTALL,
)

_INTERNAL_REASONING_TAG_PATTERN = re.compile(
    r"</?\s*(thinking|analysis|reasoning)\b[^>]*>",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class AgentAnswer:
    answer: str
    structured_content: dict | None
    tool_calls: list[str]
    usage: TokenUsage


class ProductHealthAgent:
    """Small model/tool loop that never computes health itself."""

    def __init__(
        self,
        model_provider: ModelProvider,
        tools: list[AgentTool],
        max_tool_rounds: int = 2,
    ) -> None:
        self.model_provider = model_provider
        self.tools_by_name = {tool.definition.name: tool for tool in tools}
        self.tool_definitions: list[ToolDefinition] = [
            *[tool.definition for tool in tools],
            RESPOND_WITH_CAPABILITIES_TOOL_DEFINITION,
        ]
        self.max_tool_rounds = max(1, max_tool_rounds)

    def answer(self, question: str) -> AgentAnswer:
        if not self.model_provider.is_available():
            reason = getattr(
                self.model_provider,
                "reason",
                "AI model provider is not configured.",
            )
            raise RuntimeError(str(reason))
        normalized_question = question.strip()
        if not normalized_question:
            raise ValueError("question must not be blank")
        response_language = detect_response_language(normalized_question)

        messages = [ModelMessage(role="user", text=normalized_question)]
        executed_tool_names: list[str] = []
        usage = TokenUsage()

        for round_index in range(self.max_tool_rounds):
            response = self._complete(
                messages,
                tool_choice=(
                    ToolChoice.REQUIRED if round_index == 0 else ToolChoice.AUTO
                ),
                response_language=response_language,
            )
            usage = usage.plus(response.usage)
            messages.append(
                ModelMessage(
                    role="assistant",
                    text=response.text,
                    tool_calls=response.tool_calls,
                )
            )
            if not response.tool_calls:
                if not executed_tool_names:
                    return AgentAnswer(
                        answer=CAPABILITY_FALLBACK_RESPONSE,
                        structured_content=None,
                        tool_calls=[],
                        usage=usage,
                    )
                return AgentAnswer(
                    answer=_visible_text_or_fallback(
                        response.text,
                        response_language,
                        "general",
                    ),
                    structured_content=None,
                    tool_calls=executed_tool_names,
                    usage=usage,
                )

            tool_results = []
            tool_result_names: list[str] = []
            for tool_call in response.tool_calls:
                if tool_call.name == RESPOND_WITH_CAPABILITIES_TOOL_NAME:
                    executed_tool_names.append(tool_call.name)
                    return AgentAnswer(
                        answer=_capability_message_or_fallback(tool_call.arguments),
                        structured_content=None,
                        tool_calls=executed_tool_names,
                        usage=usage,
                    )
                tool = self.tools_by_name.get(tool_call.name)
                if tool is None:
                    raise ValueError(f"Unsupported tool: {tool_call.name}")
                executed_tool_names.append(tool_call.name)
                tool_results.append(
                    ToolResult(
                        tool_call_id=tool_call.id,
                        result=tool.execute(tool_call.arguments),
                    )
                )
                tool_result_names.append(tool_call.name)
            structured_content = _select_structured_content(
                tool_result_names,
                tool_results,
            )
            if structured_content is not None:
                messages.append(ModelMessage(role="tool", tool_results=tool_results))
                final_response = self._complete_intro(
                    messages,
                    response_language=response_language,
                )
                usage = usage.plus(final_response.usage)
                return AgentAnswer(
                    answer=_intro_from_response_or_fallback(
                        final_response,
                        response_language,
                        str(structured_content.get("scope") or "general"),
                    ),
                    structured_content=structured_content,
                    tool_calls=executed_tool_names,
                    usage=usage,
                )
            messages.append(ModelMessage(role="tool", tool_results=tool_results))

        final_response = self._complete(
            messages,
            tool_choice=ToolChoice.AUTO,
            response_language=response_language,
        )
        usage = usage.plus(final_response.usage)
        return AgentAnswer(
            answer=_visible_text_or_fallback(
                final_response.text,
                response_language,
                "general",
            ),
            structured_content=None,
            tool_calls=executed_tool_names,
            usage=usage,
        )

    def _complete(
        self,
        messages: list[ModelMessage],
        tool_choice: ToolChoice,
        response_language: DetectedLanguage,
    ) -> ModelResponse:
        return self.model_provider.complete(
            system_prompt=_request_system_prompt(response_language),
            messages=messages,
            tools=self.tool_definitions,
            tool_choice=tool_choice,
        )

    def _complete_intro(
        self,
        messages: list[ModelMessage],
        response_language: DetectedLanguage,
    ) -> ModelResponse:
        return self.model_provider.complete(
            system_prompt=_request_system_prompt(response_language),
            messages=messages,
            tools=[RESPOND_WITH_PRODUCT_HEALTH_INTRO_TOOL_DEFINITION],
            tool_choice=ToolChoice.REQUIRED,
        )


def _request_system_prompt(response_language: DetectedLanguage) -> str:
    return "\n\n".join(
        [
            SYSTEM_PROMPT,
            RESPONSE_LANGUAGE_PROMPT_TEMPLATE.format(
                name=response_language.name,
                code=response_language.code,
            ),
        ]
    )


def _structured_content_for_tool_result(tool_name: str, result: dict) -> dict | None:
    if tool_name == "list_unhealthy_items":
        return _build_unhealthy_items_content(result)
    if tool_name == "get_product_health":
        return _build_product_health_item_content(result)
    return None


def _select_structured_content(
    tool_names: list[str],
    tool_results: list[ToolResult],
) -> dict | None:
    named_results = list(zip(tool_names, tool_results, strict=False))
    for tool_name, tool_result in reversed(named_results):
        if tool_name != "get_product_health":
            continue
        structured_content = _structured_content_for_tool_result(
            tool_name,
            tool_result.result,
        )
        if structured_content is not None:
            return structured_content
        return None

    for tool_name, tool_result in reversed(named_results):
        if tool_name != "list_unhealthy_items":
            continue
        structured_content = _structured_content_for_tool_result(
            tool_name,
            tool_result.result,
        )
        if structured_content is not None:
            return structured_content
    return None


def _build_unhealthy_items_content(result: dict) -> dict:
    items = result.get("items")
    if not isinstance(items, list):
        items = []

    structured_items = _compact_unhealthy_items(items)
    return {
        "type": "product_health",
        "scope": "unhealthy_items",
        "items": structured_items,
    }


def _build_product_health_item_content(result: dict) -> dict | None:
    if result.get("found") is not True:
        return None
    item = result.get("item")
    if not isinstance(item, dict):
        return None
    related_items = _list_or_empty(result.get("relatedUnhealthyItems"))
    item_lookup = {
        item_id: related_item
        for related_item in related_items
        if isinstance(related_item, dict)
        for item_id in [_text(related_item.get("itemId"))]
        if item_id
    }
    item_id = _text(item.get("itemId"))
    if item_id:
        item_lookup[item_id] = item
    return {
        "type": "product_health",
        "scope": "item",
        "items": [_structured_health_item(item, item_lookup)],
    }


def _compact_unhealthy_items(items: list[object]) -> list[dict]:
    unhealthy_by_id: dict[str, dict] = {}
    ordered_ids: list[str] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        item_id = _text(item.get("itemId"))
        if not item_id or item_id in unhealthy_by_id:
            continue
        unhealthy_by_id[item_id] = item
        ordered_ids.append(item_id)

    referenced_dependency_ids: set[str] = set()
    for item_id in ordered_ids:
        item = unhealthy_by_id[item_id]
        for dependency in _list_or_empty(item.get("affectingDependencies")):
            if not isinstance(dependency, dict):
                continue
            dependency_id = _text(dependency.get("itemId"))
            if dependency_id:
                referenced_dependency_ids.add(dependency_id)

    top_level_ids = [
        item_id for item_id in ordered_ids if item_id not in referenced_dependency_ids
    ]
    if ordered_ids and not top_level_ids:
        top_level_ids = ordered_ids

    return [
        _structured_health_item(unhealthy_by_id[item_id], unhealthy_by_id)
        for item_id in top_level_ids
    ]


def _structured_health_item(
    item: dict,
    item_lookup: dict[str, dict] | None = None,
) -> dict:
    item_id = _text(item.get("itemId")) or ""
    return {
        "item_id": item_id,
        "title": _text(item.get("title")) or item_id or "Unknown item",
        "state": _text(item.get("state")) or "UNKNOWN",
        "signals": _structured_unhealthy_signals(item.get("signals")),
        "affecting_dependencies": _structured_affecting_dependencies(
            item.get("affectingDependencies"),
            item_lookup,
        ),
    }


def _structured_unhealthy_signals(value: object) -> list[dict]:
    signals = []
    for signal in _list_or_empty(value):
        if not isinstance(signal, dict):
            continue
        state = _text(signal.get("state"))
        if state == "UP":
            continue
        signal_id = _text(signal.get("id")) or ""
        title = _text(signal.get("title")) or signal_id
        if signal_id and title and state:
            signals.append({"id": signal_id, "title": title, "state": state})
    return signals


def _structured_affecting_dependencies(
    value: object,
    item_lookup: dict[str, dict] | None = None,
) -> list[dict]:
    dependencies = []
    seen_ids = set()
    for dependency in _list_or_empty(value):
        if not isinstance(dependency, dict):
            continue
        item_id = _text(dependency.get("itemId"))
        if not item_id or item_id in seen_ids:
            continue
        title = _text(dependency.get("title")) or item_id
        state = _text(dependency.get("state"))
        if title and state:
            dependency_item = item_lookup.get(item_id) if item_lookup else None
            own_signals = (
                _structured_unhealthy_signals(dependency_item.get("signals"))
                if isinstance(dependency_item, dict)
                else []
            )
            dependencies.append(
                {
                    "item_id": item_id,
                    "title": title,
                    "state": state,
                    "signals": own_signals,
                }
            )
            seen_ids.add(item_id)
    return dependencies


def _list_or_empty(value: object) -> list[object]:
    return value if isinstance(value, list) else []


def _capability_message_or_fallback(arguments: dict) -> str:
    message = _text(arguments.get("message"))
    if message is None:
        return CAPABILITY_FALLBACK_RESPONSE
    if len(message) > 300:
        return CAPABILITY_FALLBACK_RESPONSE
    if _INTERNAL_REASONING_TAG_PATTERN.search(message):
        return CAPABILITY_FALLBACK_RESPONSE
    return message


def _visible_text_or_fallback(
    value: object,
    response_language: DetectedLanguage,
    scope: str,
) -> str:
    text = _strip_internal_reasoning(value)
    if text is None:
        return _localized_intro_fallback(response_language, scope)
    if len(text) > 300:
        return _localized_intro_fallback(response_language, scope)
    return text


def _intro_from_response_or_fallback(
    response: ModelResponse,
    response_language: DetectedLanguage,
    scope: str,
) -> str:
    for tool_call in response.tool_calls:
        if tool_call.name != RESPOND_WITH_PRODUCT_HEALTH_INTRO_TOOL_NAME:
            continue
        introduction = _visible_text_or_fallback(
            tool_call.arguments.get("introduction"),
            response_language,
            scope,
        )
        if len(introduction) <= 220:
            return introduction
        return _localized_intro_fallback(response_language, scope)
    return _visible_text_or_fallback(response.text, response_language, scope)


def _strip_internal_reasoning(value: object) -> str | None:
    text = _text(value)
    if text is None:
        return None
    text = _INTERNAL_REASONING_BLOCK_PATTERN.sub("", text)
    text = _INTERNAL_REASONING_TAG_PATTERN.sub("", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text or None


def _localized_intro_fallback(
    response_language: DetectedLanguage,
    scope: str,
) -> str:
    if response_language.code == "ru":
        if scope == "item":
            return "Вот текущие данные о состоянии выбранного элемента."
        if scope in {"product_health", "unhealthy_items"}:
            return "Вот текущие данные Product Health."
        return "Вот текущий ответ Product Health."
    if response_language.code in {"sr", "hr", "bs"}:
        if scope == "item":
            return "Evo trenutnog stanja izabrane stavke."
        if scope in {"product_health", "unhealthy_items"}:
            return "Evo trenutnih Product Health podataka."
        return "Evo trenutnog Product Health odgovora."
    if scope == "item":
        return "Here is the current health for the selected item."
    if scope in {"product_health", "unhealthy_items"}:
        return "Here are the current Product Health results."
    return "Here is the current Product Health response."


def _text(value: object) -> str | None:
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    return stripped or None
