services:
  dummy-java:
    build:
      context: services-demo/dummy-java

  dummy-python:
    build:
      context: services-demo/dummy-python

  dummy-javascript:
    build:
      context: services-demo/dummy-javascript
