services:
  aggregator:
    build:
      context: .
    environment:
      JAVA_OPTS: >
        -XX:MaxRAMPercentage=75.0
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1h"
      - "--storage.tsdb.retention.size=50MB"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./.temp/prometheus/data:/prometheus
    ports:
      - "9090:9090"

  dummy-java:
    build:
      context: ./dummy-services/java
    ports:
      - "8081:8080"

  dummy-python:
    build:
      context: ./dummy-services/python
    ports:
      - "8082:8080"

  dummy-javascript:
    build:
      context: ./dummy-services/javascript
    ports:
      - "8083:8080"
