services:
  aggregator:
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  aggregator-ui:
    ports:
      - "3000:3000"

  grafana:
    ports:
      - "3001:3000"

  prometheus:
    ports:
      - "9090:9090"
