services:
  payments-api:
    build:
      context: dummy-services/java

  edge-gateway:
    build:
      context: dummy-services/python

  customer-db:
    build:
      context: dummy-services/javascript
