# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

minimum_pre_commit_version = "3.7.0"
default_stages = ["pre-commit"]
default_install_hook_types = ["pre-commit", "pre-push"]
exclude = '^(\.git/|\.idea/|\.venv/|\.temp/|node_modules/)'

[[repos]]
repo = "local"
hooks = [
  {
    id = "qa-pre-commit",
    name = "qa pre-commit",
    entry = "python tools/git_hooks/hook_pre_commit.py",
    language = "python",
    pass_filenames = false,
    stages = ["pre-commit"]
  },
  {
    id = "qa-pre-push",
    name = "qa pre-push",
    entry = "python tools/git_hooks/hook_pre_push.py",
    language = "python",
    pass_filenames = false,
    stages = ["pre-push"]
  }
]
