server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

catalog:
  path: file:./config/empty/catalog.yaml

health:
  checks-path: file:./config/empty/health-checks.yaml
