server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

catalog:
  path: classpath:empty/catalog.yaml

health:
  checks-path: classpath:empty/health-checks.yaml
