# yaml-language-server: $schema=../schemas/catalog-item-actors.schema.yaml
itemActors:
  - itemId: it_e7f7ec2d
    actorId: ac_g6k1t9rv
  - itemId: it_e7f7ec2d
    actorId: ac_j5d2m8pf
  - itemId: it_e7f7ec2d
    actorId: ac_h2c9r6vy

  - itemId: it_51dae4dd
    actorId: ac_n5b3q8lz
  - itemId: it_51dae4dd
    actorId: ac_b9x4k7rc
  - itemId: it_51dae4dd
    actorId: ac_f8m2c7tr

  - itemId: it_9d9e5627
    actorId: ac_l6v3s9jb
  - itemId: it_9d9e5627
    actorId: ac_q7n3v8mt
  - itemId: it_9d9e5627
    actorId: ac_h2c9r6vy

  - itemId: it_6307a2a8
    actorId: ac_g6k1t9rv
  - itemId: it_6307a2a8
    actorId: ac_j5d2m8pf
  - itemId: it_5b917d99
    actorId: ac_g6k1t9rv
  - itemId: it_5b917d99
    actorId: ac_j5d2m8pf
  - itemId: it_8be9ba4f
    actorId: ac_g6k1t9rv
  - itemId: it_8be9ba4f
    actorId: ac_j5d2m8pf
  - itemId: it_144bbdb0
    actorId: ac_w2h7m4pd
  - itemId: it_144bbdb0
    actorId: ac_j5d2m8pf
  - itemId: it_008a7af7
    actorId: ac_w2h7m4pd
  - itemId: it_008a7af7
    actorId: ac_j5d2m8pf
  - itemId: it_1668c093
    actorId: ac_n3q8w6zd
  - itemId: it_1668c093
    actorId: ac_c7v1b4nk
  - itemId: it_1668c093
    actorId: ac_t4p6h1ks
  - itemId: it_6c7923ab
    actorId: ac_u7m1k5vr
  - itemId: it_6c7923ab
    actorId: ac_j5d2m8pf
  - itemId: it_43ab1049
    actorId: ac_w2h7m4pd
  - itemId: it_43ab1049
    actorId: ac_j5d2m8pf

  - itemId: it_571c410e
    actorId: ac_n5b3q8lz
  - itemId: it_571c410e
    actorId: ac_b9x4k7rc
  - itemId: it_c51a1ccc
    actorId: ac_n5b3q8lz
  - itemId: it_c51a1ccc
    actorId: ac_b9x4k7rc
  - itemId: it_0387f962
    actorId: ac_n5b3q8lz
  - itemId: it_0387f962
    actorId: ac_b9x4k7rc
  - itemId: it_978f32ea
    actorId: ac_n5b3q8lz
  - itemId: it_978f32ea
    actorId: ac_b9x4k7rc
  - itemId: it_ef57ee00
    actorId: ac_p4t9x2cb
  - itemId: it_ef57ee00
    actorId: ac_h9p3m6tx
  - itemId: it_906f7e0d
    actorId: ac_d8f3v7hl
  - itemId: it_906f7e0d
    actorId: ac_b9x4k7rc
  - itemId: it_05c82f52
    actorId: ac_d8f3v7hl
  - itemId: it_05c82f52
    actorId: ac_b9x4k7rc

  - itemId: it_5c743f44
    actorId: ac_r1m8c6px
  - itemId: it_5c743f44
    actorId: ac_q7n3v8mt
  - itemId: it_741e7f6b
    actorId: ac_r1m8c6px
  - itemId: it_741e7f6b
    actorId: ac_q7n3v8mt
  - itemId: it_6e67d308
    actorId: ac_y5r4c8mt
  - itemId: it_6e67d308
    actorId: ac_q7n3v8mt
  - itemId: it_d01a646d
    actorId: ac_f3p7d1qw
  - itemId: it_d01a646d
    actorId: ac_q7n3v8mt
  - itemId: it_bee18e53
    actorId: ac_r1m8c6px
  - itemId: it_bee18e53
    actorId: ac_q7n3v8mt
  - itemId: it_a0a28b85
    actorId: ac_t9v2k4hs
  - itemId: it_a0a28b85
    actorId: ac_q7n3v8mt
  - itemId: it_4869434a
    actorId: ac_s6j2n9qw
  - itemId: it_4869434a
    actorId: ac_l2d8q5rf
  - itemId: it_e8e0d47a
    actorId: ac_y5r4c8mt
  - itemId: it_e8e0d47a
    actorId: ac_q7n3v8mt
  - itemId: it_5622ffff
    actorId: ac_t9v2k4hs
  - itemId: it_5622ffff
    actorId: ac_q7n3v8mt
  - itemId: it_5d0def3d
    actorId: ac_t9v2k4hs
  - itemId: it_5d0def3d
    actorId: ac_q7n3v8mt
  - itemId: it_ccf17b90
    actorId: ac_s6j2n9qw
  - itemId: it_ccf17b90
    actorId: ac_q7n3v8mt
  - itemId: it_e6af80a7
    actorId: ac_s6j2n9qw
  - itemId: it_e6af80a7
    actorId: ac_q7n3v8mt
  - itemId: it_352b4411
    actorId: ac_y5r4c8mt
  - itemId: it_352b4411
    actorId: ac_q7n3v8mt
  - itemId: it_ae13d093
    actorId: ac_y5r4c8mt
  - itemId: it_ae13d093
    actorId: ac_q7n3v8mt

  - itemId: it_5a9ca947
    actorId: ac_w2h7m4pd
  - itemId: it_5a9ca947
    actorId: ac_j5d2m8pf
  - itemId: it_31cdf080
    actorId: ac_n3q8w6zd
  - itemId: it_31cdf080
    actorId: ac_c7v1b4nk
  - itemId: it_31cdf080
    actorId: ac_t4p6h1ks
  - itemId: it_b0833df4
    actorId: ac_u7m1k5vr
  - itemId: it_b0833df4
    actorId: ac_j5d2m8pf
  - itemId: it_ca854f7f
    actorId: ac_n5b3q8lz
  - itemId: it_ca854f7f
    actorId: ac_j5d2m8pf

  - itemId: it_48bb5977
    actorId: ac_p4t9x2cb
  - itemId: it_48bb5977
    actorId: ac_h9p3m6tx
  - itemId: it_34b1b4e7
    actorId: ac_d8f3v7hl
  - itemId: it_34b1b4e7
    actorId: ac_b9x4k7rc
  - itemId: it_0d5a82d5
    actorId: ac_n5b3q8lz
  - itemId: it_0d5a82d5
    actorId: ac_b9x4k7rc
  - itemId: it_4395c1de
    actorId: ac_n5b3q8lz
  - itemId: it_4395c1de
    actorId: ac_b9x4k7rc

  - itemId: it_71574a7b
    actorId: ac_y5r4c8mt
  - itemId: it_71574a7b
    actorId: ac_q7n3v8mt
  - itemId: it_92628e0a
    actorId: ac_t9v2k4hs
  - itemId: it_92628e0a
    actorId: ac_q7n3v8mt
  - itemId: it_51735b03
    actorId: ac_s6j2n9qw
  - itemId: it_51735b03
    actorId: ac_l2d8q5rf
  - itemId: it_8f468246
    actorId: ac_y5r4c8mt
  - itemId: it_8f468246
    actorId: ac_q7n3v8mt

  - itemId: it_b61910c1
    actorId: ac_g6k1t9rv
  - itemId: it_b61910c1
    actorId: ac_j5d2m8pf
  - itemId: it_1151701c
    actorId: ac_w2h7m4pd
  - itemId: it_1151701c
    actorId: ac_j5d2m8pf
  - itemId: it_2484e0db
    actorId: ac_w2h7m4pd
  - itemId: it_2484e0db
    actorId: ac_j5d2m8pf
  - itemId: it_fbb05062
    actorId: ac_w2h7m4pd
  - itemId: it_fbb05062
    actorId: ac_j5d2m8pf
  - itemId: it_96952012
    actorId: ac_n3q8w6zd
  - itemId: it_96952012
    actorId: ac_c7v1b4nk
  - itemId: it_96952012
    actorId: ac_t4p6h1ks
  - itemId: it_65839693
    actorId: ac_n3q8w6zd
  - itemId: it_65839693
    actorId: ac_c7v1b4nk
  - itemId: it_3ca8ec85
    actorId: ac_u7m1k5vr
  - itemId: it_3ca8ec85
    actorId: ac_j5d2m8pf
  - itemId: it_4c046b1d
    actorId: ac_u7m1k5vr
  - itemId: it_4c046b1d
    actorId: ac_j5d2m8pf
  - itemId: it_9e60bdd7
    actorId: ac_w2h7m4pd
  - itemId: it_9e60bdd7
    actorId: ac_j5d2m8pf
  - itemId: it_3160377e
    actorId: ac_w2h7m4pd
  - itemId: it_3160377e
    actorId: ac_j5d2m8pf

  - itemId: it_bd3e8b82
    actorId: ac_n5b3q8lz
  - itemId: it_bd3e8b82
    actorId: ac_b9x4k7rc
  - itemId: it_9ead5a94
    actorId: ac_n5b3q8lz
  - itemId: it_9ead5a94
    actorId: ac_b9x4k7rc
  - itemId: it_9de17f36
    actorId: ac_p4t9x2cb
  - itemId: it_9de17f36
    actorId: ac_h9p3m6tx
  - itemId: it_ed0d04bb
    actorId: ac_p4t9x2cb
  - itemId: it_ed0d04bb
    actorId: ac_h9p3m6tx
  - itemId: it_20cb3376
    actorId: ac_d8f3v7hl
  - itemId: it_20cb3376
    actorId: ac_b9x4k7rc
  - itemId: it_7199280d
    actorId: ac_d8f3v7hl
  - itemId: it_7199280d
    actorId: ac_b9x4k7rc
  - itemId: it_2df0c55c
    actorId: ac_d8f3v7hl
  - itemId: it_2df0c55c
    actorId: ac_b9x4k7rc
  - itemId: it_116e2e82
    actorId: ac_n5b3q8lz
  - itemId: it_116e2e82
    actorId: ac_b9x4k7rc
  - itemId: it_a6854c60
    actorId: ac_n5b3q8lz
  - itemId: it_a6854c60
    actorId: ac_b9x4k7rc
  - itemId: it_a6854c60
    actorId: ac_f8m2c7tr

  - itemId: it_9c69814b
    actorId: ac_f3p7d1qw
  - itemId: it_9c69814b
    actorId: ac_q7n3v8mt
  - itemId: it_9c69814b
    actorId: ac_h2c9r6vy
  - itemId: it_0c7f7cbf
    actorId: ac_f3p7d1qw
  - itemId: it_0c7f7cbf
    actorId: ac_q7n3v8mt
  - itemId: it_40d8cd7c
    actorId: ac_f3p7d1qw
  - itemId: it_40d8cd7c
    actorId: ac_q7n3v8mt
  - itemId: it_12a5d380
    actorId: ac_y5r4c8mt
  - itemId: it_12a5d380
    actorId: ac_q7n3v8mt
  - itemId: it_5e0132b8
    actorId: ac_f3p7d1qw
  - itemId: it_5e0132b8
    actorId: ac_q7n3v8mt
  - itemId: it_7e7405d3
    actorId: ac_t9v2k4hs
  - itemId: it_7e7405d3
    actorId: ac_q7n3v8mt
  - itemId: it_6cab1e6f
    actorId: ac_s6j2n9qw
  - itemId: it_6cab1e6f
    actorId: ac_l2d8q5rf
  - itemId: it_984c1c25
    actorId: ac_s6j2n9qw
  - itemId: it_984c1c25
    actorId: ac_l2d8q5rf
  - itemId: it_86ccee33
    actorId: ac_y5r4c8mt
  - itemId: it_86ccee33
    actorId: ac_q7n3v8mt
  - itemId: it_29082314
    actorId: ac_y5r4c8mt
  - itemId: it_29082314
    actorId: ac_q7n3v8mt
