server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

catalog:
  base-url: ${CATALOG_BASE_URL:http://catalog:8080}

feedback:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
