server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

catalog:
  items-path: file:./catalog-items.yaml
  dependencies-path: file:./catalog-dependencies.yaml
  items-schema-path: file:./schemas/catalog-items.schema.yaml
  dependencies-schema-path: file:./schemas/catalog-dependencies.schema.yaml

health:
  http-poll:
    definition-path: file:./signals-http-poll.yaml
    schema-path: file:./schemas/signals-http-poll.schema.yaml

feedback:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
