server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

catalog:
  path: file:./catalog-definition.yaml

health:
  http-poll:
    definition-path: file:./http-poll-signals.yaml

feedback:
  store-type: local-files
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  local-files:
    path: ./feedback.ndjson
  dynamo:
    table-name: aggregator_feedback
